# Generated by Django 5.0.7 on 2024-07-14 11:42

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.timezone),
        ),
    ]
